repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
      - id: requirements-txt-fixer
      - id: check-docstring-first
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==23.1.0]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.7.3]
    - id: nbqa-isort
      additional_dependencies: [isort==5.6.4]